#!/usr/bin/perl
use strict;
use warnings;
use Time::HiRes qw(sleep);

my $FIFO = '/tmp/klomplayer_fifo';
my $PID_FILE = '/tmp/klomplayer_updater_pid';
system "kill -9 `cat $PID_FILE`";
system "echo $$ > $PID_FILE";

while(1){
  sleep 0.5;
  system "echo pausing_keep_force get_time_length > $FIFO";
  system "echo pausing_keep_force get_time_pos > $FIFO";
}
