#!/usr/bin/perl
use strict;
use warnings;

my @libs = `klomp-lib`;
chomp foreach @libs;

for my $lib(@libs){
  print "\nHandling library: $lib\n";

  system 'klomp-db', '-m', $lib;
  system 'klomp-db', '-u', $lib;
}

for my $lib(@libs){
  my $dir = `klomp-lib -l $lib`;
  chomp $dir;
  my $flacMirrorDir = `klomp-lib -f $lib`;
  chomp $flacMirrorDir;
  system "mkdir", "-p", $flacMirrorDir if $flacMirrorDir;
  
  if(-e $flacMirrorDir and -e $dir){
    print "\nflacmirror for: $lib\n";
    system "flacmirror $dir $flacMirrorDir";
  }
}
