#!/usr/bin/perl
use strict;
use warnings;

my $usage = "$0 OPTS
  OPTS:  --force-flacs, --no-force-flacs
               If a library has a flacmirror on the destination,
               flacs are omitted. This flag makes them never be omitted.
";

sub main(@){
  my $dest = shift;
  my $forceFlacs = shift() || '--no-force-flacs';
  die $usage if not defined $dest or $forceFlacs !~ /^(--(no-)?force-flacs)$/;

  
}




&main(@ARGV);
#SRC=~/Desktop/Music
#DEST=/media/mmc1/Music
#klomp-update
#echo moving files around on the destination to prepare for library sync
#presync $SRC/Library root@`n900`:$DEST/Library
#
#echo Syncing library, sans flac
#rsync -av --exclude=*.flac --del $SRC/Library/ root@`n900`:$DEST/Library
#
#echo moving files around on the destination to prepare for flacmirror sync
#presync $SRC/flacmirror root@`n900`:$DEST/flacmirror
#
#echo Syncing flacmirror oggs
#rsync -av $SRC/flacmirror/ --del root@`n900`:$DEST/flacmirror
#echo chown $DEST on n900
#ssh root@`n900` chown user.users -R $DEST
#
#echo copying .klompdb to n900
#scp ~/.klompdb root@`n900`:/home/user
#ssh root@`n900` chown user.users /home/user/.klompdb
