#!/usr/bin/perl
use strict;
use warnings;

if(@ARGV == 0){
  die "Usage: $0 <file> <file 2> <file 3> ...\n";
}

for my $file(@ARGV){
  my $path = $file;
  $file =~ s/'/'\\''/g;

  my $title='';
  my $artist='';
  my $album='';
  my $number='';
  my $date='';
  my $genre='';
  if($file =~ /.(mp3|ogg|flac)/i){
    my $lltag = `lltag -S '$file'`;
    if($lltag =~ m/^\s*TITLE=(.*)$/mix){
      $title = $1;
    }
    if($lltag =~ m/^\s*ARTIST=(.*)$/mix){
      $artist = $1;
    }
    if($lltag =~ m/^\s*ALBUM=(.*)$/mix){
      $album = $1;
    }
    if($lltag =~ m/^\s*NUMBER=(.*)$/mix){
      $number = $1;
    }
    if($lltag =~ m/^\s*DATE=(.*)$/mix){
      $date = $1;
    }
    if($lltag =~ m/^\s*GENRE=(.*)$/mix){
      $genre = $1;
    }
  }elsif($file =~ /.(mp4|m4a|m4p|m4v|m4b)/i){
    my $atomic = `AtomicParsley '$file' -t`;
    if($atomic =~ m/^Atom\ "©NAM"\ contains:\ (.*)$/mix){
      $title = $1;
    }
    if($atomic =~ m/^Atom\ "©ART"\ contains:\ (.*)$/mix){
      $artist = $1;
    }
    if($atomic =~ m/^Atom\ "©ALB"\ contains:\ (.*)$/mix){
      $album = $1;
    }
    if($atomic =~ m/^Atom\ "trkn"\ contains:\ (.*)$/mix){
      $number = $1;
    }
    if($atomic =~ m/^Atom\ "©day"\ contains:\ (.*)$/mix){
      $date = $1;
    }
    if($atomic =~ m/^Atom\ "(?:gnre|©gen)"\ contains:\ (.*)$/mix){
      $genre = $1;
    }
  }else{
    die "Could not find file: $path";
  }
  print "
    path=$path
    title=$title
    artist=$artist
    album=$album
    number=$number
    date=$date
    genre=$genre
  ";
}
