#!/usr/bin/perl
use strict;
use warnings;
use lib "/opt/klomp/lib";
use Klomp::Files;

my $files = Klomp::Files::allKlompFiles();

my $okFiles = join "|", sort keys %$files;

my $usage = "Usage:
  $0 [-n] $okFiles
    Print the absolute path to the file.

  -n    do not output a trailing newline
";

sub main(@){
  my $newline = 1;
  if(@_ > 0 and $_[0] eq '-n'){
    $newline = 0;
    shift;
  }

  my $arg = shift() || '';
  if($arg =~ /^($okFiles)$/){
    print "$$files{$arg}";
  }else{
    die $usage;
  }

  print "\n" if $newline;
}

&main(@ARGV);
