#!/usr/bin/perl
use strict;
use warnings;
use lib "/opt/klomp/lib";
use Klomp::Files;
use Klomp::Lib;
use Klomp::Tag;

my @songSuffixes = ('mp3', 'flac', 'ogg', 'm4a', 'wma', 'wav');
                    #aiff

my @infoCols = qw(library relpath filesize modified md5sum);
my @tagCols = qw(title artist album number date genre);
my @guessTagCols = map{$_ . "_guess"} @tagCols;
my @searchableCols = (@infoCols, @tagCols);
my @allCols = (@infoCols, @tagCols, @guessTagCols);

my $defaultDb = Klomp::Files::klompFile("db");

sub fsize($);
sub mtime($);
sub shell(@);
sub shellQuiet(@);
sub runSql($$;@);
sub runSqlBatch($\@;@);
sub cols($);
sub addSongs($$$$);
sub wrapGuessCol($);
sub create($);
sub update($$$);
sub missing($$);
sub add($$$$);
sub search($$$$$$);
sub validateQuery($);
sub getSubQuerySql($$);
sub info($$);

my $usage = "Usage: 
 $0 [db-path] -c|--create
   Make an empty sqlite db with necessary structures

 $0 [db-path] -u|--update [--quick] [lib lib ...]
   Add or update the info in the db for music files in the given libs (or all)

 $0 [db-path] -m|--missing [--quick] [lib lib ...]
   Check for missing files in given libs (or all), and prompt for removal.

 $0 [db-path] -a|--add lib song-rel-path
   Add or update the info in the db for the file at song-rel-path in lib

 $0 [db-path] -i|--info [song-rel-path or song-abs-path]
   Query for the info for a song, given the path of the song

 $0 [db-path] -s|--search query [OPTS]
   Query for relative paths to songs in given libs (or all), or more info.
   optional OPTS:
   -v|--verbose            print SQL to STDERR before running it
   --lib lib               optional libs to search (all if not given)
                           {can appear multiple times}
   -l|--limit LIMIT        optional integer limit on number of rows returned
   --col COL               optional col; returned as csv if any specified
                           {can appear multiple times}
                           by default, just relpath is returned.
                           allowed values: \n   @searchableCols

 [db-path] is optional and cannot start with a hyphen. {arg parsing => im lazy}
 if not given, the default is '$defaultDb'
";

sub main(@){
  die $usage if @_ == 0 or $_[0] =~ /^(-h|--help)/;

  my $db;
  if($_[0] !~ /^-/){
    $db = shift;
  }else{
    $db = $defaultDb;
  }

  my $cmd = shift() || '';

  if($cmd =~ /^(-c|--create)$/ and @_ == 0){
    if(-e $db){
      die "'$db' exists already\n";
    }
    create($db);
  }elsif($cmd =~ /^(-u|--update)$/){
    my $quick = 0;
    if(@_ > 0 and $_[0] =~ /^(--quick)$/){
      $quick = 1;
      shift;
    }
    update($db, $quick, \@_);
  }elsif($cmd =~ /^(-m|--missing)$/){
    missing($db, \@_);
  }elsif($cmd =~ /^(-a|--add)$/ and @_ >= 2){
    my $quick = 0;
    if(@_ > 0 and $_[0] =~ /^(--quick)$/){
      $quick = 1;
      shift;
    }
    my $lib = shift;
    my $songRelPath = shift;
    add($db, $lib, $quick, $songRelPath);
  }elsif($cmd =~ /^(-i|--info)$/ and @_ == 1){
    my $songRelPath = shift;
    info($db, $songRelPath);
  }elsif($cmd =~ /^(-s|--search)$/ and @_ >= 1){
    my $query = shift;

    my $verbose = 0;
    my @libs;
    my $limit = 0;
    my @cols;
    my $mode = 'playlist';
    while(@_){
      my $arg = shift;
      if($arg =~ /^(-v|--verbose)$/){
        $verbose = 1;
      }elsif($arg =~ /^(-l|--limit)$/ && @_>0){
        $limit = shift;
        die $usage if $limit !~ /^\d+$/;
      }elsif($arg =~ /^(--col)$/ && @_>0){
        my $col = shift;
        my %isAllowed = map {$_ => 1} @searchableCols;
        die $usage if not defined $isAllowed{$col};
        push @cols, $col;
      }elsif($arg =~ /^(--lib)$/ && @_>0){
        my $lib = shift;
        push @libs, $lib;
      }else{
        die $usage;
      }
    }

    search($db, $query, $verbose, $limit, \@cols, \@libs);
  }else{
    die $usage;
  }
}


sub create($){
  my $db = shift;
  if(-e $db){
    die "$db exists already\n";
  }
  runSql($db,
    "create table Songs ("
      . (join "", map {"$_ varchar,"} @allCols)
      . "PRIMARY KEY (library, relpath)"
    . ");");
}

sub update($$$){
  my $db = shift;
  my $quick= shift;
  my @libs = @{shift()};
  for my $lib(@libs){
    my $libpath = Klomp::Lib::getLibraryPath $lib;
    if(not -d $libpath){
      die "Invalid library path $libpath\n";
    }
    chdir $libpath;

    my $suffixPattern;
    for(my $i=0; $i<@songSuffixes; $i++){
      $suffixPattern .= ".*\\." . $songSuffixes[$i];
      if($i < $#songSuffixes){
        $suffixPattern .= "\\|";
      }
    }
    my @songRelPaths = shell 'find', '.', '-iregex', $suffixPattern;
    @songRelPaths = sort @songRelPaths;
    for (my $i=0; $i<@songRelPaths; $i++){
      my $songRelPath = $songRelPaths[$i];
      chomp $songRelPath;
      $songRelPath =~ s/^.\///;
      $songRelPaths[$i] = $songRelPath;
    }
    addSongs($db, $lib, $quick, \@songRelPaths);
  }
}

sub missing($$){
  my $db = shift;
  my @libs = @{shift()};
  for my $lib(@libs){
    chdir $lib;
    checkMissing($db, $lib);
  }
}

sub add($$$$){
  my $db = shift;
  my $lib = shift;
  my $quick = shift;
  my $songRelPath = shift;
  
  my @songRelPaths;
  push @songRelPaths, $songRelPath;
  addSongs($db, $lib, $quick, \@songRelPaths);
}

sub quoteTokenize($){
  my $query = shift;

  $query =~ s/~/~~/g;
  my $quoteTokens = {};

  my $newQuery = '';
  my $endOfLastQuote = 0;

  my $tokenId = 0;

  my $startQuote=0;
  my $endQuote;
 
  my $offset=0;

  my $len = length $query;
  while($offset >= 0 and $offset<$len){
    last if ($offset = index $query, '"', $offset) < 0;
    $startQuote = $offset;
    $offset++;
    while($offset >= 0 and $offset<$len){
      last if ($offset = index $query, '"', $offset) < 0;
      $endQuote = $offset;
      $offset++;
      my $nextChar = substr $query, $endQuote+1, 1;
      if($nextChar eq '"'){
        $offset++;
      }else{
        my $quoteToken = substr $query, $startQuote+1, $endQuote-$startQuote-1;
        $quoteToken =~ s/""/"/g;
        $newQuery .= substr $query, $endOfLastQuote, $startQuote-$endOfLastQuote;
        $endOfLastQuote = $endQuote+1;
        $newQuery .= "~$tokenId~";
        $$quoteTokens{$tokenId++} = $quoteToken;
        last;
      }
    }
  }
  $newQuery .= substr $query, $endOfLastQuote, $len-$endOfLastQuote;

  return ($newQuery, $quoteTokens);
}
sub quoteUntokenize($$){
  my ($query, $quoteTokens) = @_;

  for my $tokenId(keys %$quoteTokens){
    my $token = $$quoteTokens{$tokenId};
    $query =~ s/~$tokenId~/$token/;
  }

  $query =~ s/~~/~/g;
  return $query;
}

sub search($$$$$$){
  my $db = shift;
  my $query = shift;
  my $verbose = shift;
  my $limit = shift;
  my @cols = @{shift()};
  my @libs = @{shift()};

  my @allLibs = Klomp::Lib::getAllLibNames;
  my @defaultLibs = Klomp::Lib::getDefaultLibNames;
  my %okLibs = map {$_ => 1} @allLibs;

  my $all = 0;
  my $libRegex = qr/^\@([a-zA-Z0-9]+)/;
  while($query =~ /$libRegex/){
    my $lib = $1;
    if($lib eq 'all'){
      $query =~ s/$libRegex//;
      $all = 1;
    }elsif(defined $okLibs{$lib}){
      $query =~ s/$libRegex//;
      push @libs, $lib;
    }else{
      last;
    }
  }

  @libs = @defaultLibs if @libs == 0;
  @libs = () if $all;

  my $libWhere = '1=1';
  if(@libs > 0){
    $libWhere = "library in (" . (join ', ', map {"'$_'"} @libs) . ")";
  }

  if(not @cols){
    @cols = ('relpath');
  }

  my %isTagCol = map{$_ => 1} @tagCols;

  my @guessCols;
  my @namedCols;
  my @orderCols;
  for my $col(@cols){
    my $guessCol;
    if(defined $isTagCol{$col}){
      $guessCol = wrapGuessCol($col);
    }else{
      $guessCol = $col;
    }
    push @guessCols, $guessCol;
    push @namedCols, "$guessCol $col";
    if($col eq 'number'){
      push @orderCols, "number_guess";
    }else{
      push @orderCols, $guessCol;
    }
  }

  my $orderBy = "ORDER BY\n" . join(",\n      ", @orderCols);

  my $lim = $limit > 0 ? "LIMIT $limit" : '';

  my $quoteTokens;
  ($query, $quoteTokens) = quoteTokenize $query;

  $query =~ s/\s*  \(    \s*/~lparens~/gx;
  $query =~ s/\s*  \)    \s*/~rparens~/gx;
  $query =~ s/\s*  \&\&  \s*/~and~/gx;
  $query =~ s/\s*  \|\|  \s*/~or~/gx;
  $query =~ s/\s*  \+\+  \s*/~or~/gx;
  $query =~ s/\s+/~and~/g;

  my $queryParts = [];
  while($query =~ /(.*?)(~lparens~|~rparens~|~and~|~or~|$)/g){
    push @$queryParts, ['subquery', $1] if $1 ne "";
    push @$queryParts, ["$2"] if $2 ne "";
  }

  $queryParts = validateQuery $queryParts;

  my $where = '';
  for my $part(@$queryParts){
    my $type = $$part[0];
    if($type eq "~lparens~"){
      $where .= "\n (\n";
    }elsif($type eq "~rparens~"){
      $where .= "\n )\n";
    }elsif($type eq "~and~"){
      $where .= "\n  and\n";
    }elsif($type eq "~or~"){
      $where .= "\n  or\n";
    }elsif($type eq "subquery"){
      my $q = $$part[1];
      $where .= "  (" . getSubQuerySql($q, $quoteTokens) . "\n  )";
    }else{
      die "Unknown query part type: $type\n";
    }
  }

  my $selCols = join "\n       ,", @namedCols;
  my $sql = ''
    . "select $selCols \n"
    . "from Songs \n"
    . "where $libWhere and (\n$where\n)\n$orderBy\n$lim;";

  print STDERR "--\n$sql\n--\n" if $verbose;
  
  if(@cols > 1){
    print runSql $db, $sql, '-csv';
  }else{
    print runSql $db, $sql;
  }
}

sub validateQuery($){
  my $queryParts = shift();
  my $newQueryParts = [];

  for(my $i=0; $i<@$queryParts; $i++){
    my $type = $$queryParts[$i][0];
    my $prevType = $i-1 >= 0 ? $$queryParts[$i-1][0] : 'undef';

    my @okPrev;
    if($type eq "subquery"){
      @okPrev = qw(undef ~lparens~ ~and~ ~or~);
    }elsif($type eq "~lparens~"){
      @okPrev = qw(undef ~lparens~ ~and~ ~or~);
    }elsif($type eq "~rparens~"){
      @okPrev = qw(subquery ~rparens~);
    }elsif($type eq "~and~"){
      @okPrev = qw(subquery ~rparens~);
    }elsif($type eq "~or~"){
      @okPrev = qw(subquery ~rparens~);
    }
    my %okPrevHash = map {$_=>1} @okPrev;
    if(not defined $okPrevHash{$prevType}){
      die "'$type' is after '$prevType': only '@okPrev' is allowed\n";
    }
    push @$newQueryParts, $$queryParts[$i];
  }

  return $newQueryParts;
}

# turns search words into SQL queries
sub getSubQuerySql($$){
  my ($q, $quoteTokens) = @_;

  my %columnNames = (
    t => ["title", "title_guess"],
    l => ["album", "album_guess"],
    a => ["artist", "artist_guess"],
    g => ["genre"],
    p => ["relpath"],
    n => ["number", "number_guess"],
  );

  my $negate = $q =~ s/^!//;

  my $colStr;
  if($q =~ s/^@([tlagpn]+)//){
    $colStr = $1;
  }else{
    $colStr = "tla";
  }
  my %colChars = map {$_=>1} split //, $colStr;
  my @columns = map {@{$columnNames{$_}}} keys %colChars;

  my $startAnchor = $q =~ s/^\^//;
  my $endAnchor = $q =~ s/\$$//;

  $q = quoteUntokenize $q, $quoteTokens;

  $q =~ s/'/''/g;
  $q =~ s/%/\\%/g;

  $q = "%$q" unless $startAnchor;
  $q = "$q%" unless $endAnchor;
  $q = "'$q'";

  my $compOp = $negate ? "not like" : "like";
  my $joinOp = $negate ? "and" : "or";

  return join(" $joinOp ", map{"\n      $_ $compOp $q"} @columns);
}

sub info($$){
  my $db = shift;
  my $songRelPath = shift;

  my $libWhere = '1=1';
  for my $lib(Klomp::Lib::getAllLibNames()){
    my $libpath = Klomp::Lib::getLibraryPath $lib;
    if($songRelPath =~ s/^$libpath//){
      $libWhere = "library = '$lib'";
      last;
    }
  }
  $songRelPath =~ s/^\///;
  $songRelPath =~ s/'/''/g;

  my $sql = ''
    . "select * "
    . "from Songs "
    . "where relpath = '$songRelPath' "
    . "  and $libWhere;"
    ;
  my @rows = runSql($db, $sql, '-csv', '-header');
  die "file not found in db: $songRelPath\n" if @rows < 2;
  die "more than one song found, use abs path instead of '$songRelPath'\n"
    if @rows > 2;

  my @headers = cols $rows[0];
  my @data = cols $rows[1];

  if(@headers != @data){
    die "mismatched headers and data\n";
  }
  for(my $i=0; $i<@headers; $i++){
    print $headers[$i] . "=" . $data[$i] . "\n";
  }
}

sub fsize($){
  return (stat $_[0])[7];
}
sub mtime($){
  return (stat $_[0])[9];
}


sub wrapTokens(@){
  my @tokens;
  for my $token(@_){
    my $t = $token;
    $t =~ s/'/'\\''/g;
    push @tokens, "'$t'";
  }
  return @tokens;
}

sub shellQuiet(@){
  my $cmd = join ' ', wrapTokens(@_);
  return `$cmd 2>/dev/null`;
}
sub shell(@){
  my $cmd = join ' ', wrapTokens(@_);
  return `$cmd`;
}

sub runSql($$;@){
  my $db = shift;
  my $sql = shift;

  utf8::decode($sql);
  my @tokens;
  push @tokens, 'sqlite3';
  for my $opt(@_){
    push @tokens, $opt;
  }
  push @tokens, $db;
  push @tokens, $sql;

  return shell @tokens;
}
sub runSqlBatch($\@;@){
  my $db = shift;
  my @stmts = @{shift()};
  @stmts = ("BEGIN", @stmts, "END");
  my $sql = join ";\n", @stmts;
  runSql $db, $sql, @_;
}

sub cols($){
  my $csvrow = shift;
  chomp $csvrow;
  my @cols;
  while($csvrow =~ /
    (?:
      "()"
      |
      "(.*?(?<!"))"
      |
      ([^,]+)
    )
    (?:,|$)
  /gsxi){
    my $col;
    $col = $1 if defined $1;
    $col = $2 if defined $2;
    $col = $3 if defined $3;
    $col =~ s/""/"/g;
    push @cols, $col;
  }
  return @cols;
}

sub checkMissing($$){
  my $db = shift;
  my $lib = shift;
  my $libpath = Klomp::Lib::getLibraryPath $lib;

  my @songRelPaths =
    runSql $db, "select relpath from songs where library = '$lib'";
  my $len = @songRelPaths;
  my $piece = 1+$len / 10;
  print "checking $len songs from the db for missing\n";
  my $count = 0;
  my @missing;
  my @deleteSql;
  for my $songRelPath(@songRelPaths){
    chomp $songRelPath;
    if(not -e "$libpath/$songRelPath"){
      print "$songRelPath\n";
      push @missing, $songRelPath;
      $songRelPath =~ s/'/''/g;
      push @deleteSql, ''
          . "delete from Songs "
          . "where relpath = '$songRelPath' "
          . "  and library = '$lib';\n"
          ;
    }
  }
  my $missingCount = scalar @missing;
  print "  finished, $missingCount missing\n";
  if($missingCount > 0){
    print "Remove above missing files from lib? (y/N) ";
    if(<STDIN> =~ /^y$/i){
      my $limit = 30;
      my $lastEnd = -1;
      for(my $i=$limit; $i<@deleteSql; $i+=$limit){
        my ($start, $end) = ($lastEnd+1, $i);
        print "Removing songs $start-$end\n";
        my @toRun = @deleteSql[$start .. $end];
        runSqlBatch $db, @toRun;
        $lastEnd = $i;
      }
      if($lastEnd < $#deleteSql){
        my ($start, $end) = ($lastEnd+1, $#deleteSql);
        print "Removing songs $start-$end\n";
        my @toRun = @deleteSql[$start .. $end];
        runSqlBatch $db, @toRun;
      }
    }
  }
}

sub addSongs($$$$){
  my $db = shift;
  my $lib = shift;
  my $quick = shift;
  my @songRelPaths = @{scalar shift};

  my $libpath = Klomp::Lib::getLibraryPath $lib;
  
  my %dbInfo;
  for my $line(runSql($db, 'select filesize, modified, relpath from Songs')){
    $line =~ /(\d+)\|(\d+)\|(.*)\n/;
    my @fs_mod = ($1, $2);
    $dbInfo{$3} = \@fs_mod;
  }

  my $songCount = @songRelPaths;
  my $handledCount = 0;
  my $skippedCount = 0;
  print "Adding/updating $songCount songs from the filesystem\n";
  
  my $count = 0;
  my @stmts = ();
  my $limit = 50;
  for my $songRelPath(@songRelPaths){
    my ($dbSize, $dbMod);
    
    my $info = $dbInfo{$songRelPath};
    my $dbExists = defined $info;
    if($dbExists){
      my @infoArr = @{$info};
      $dbSize = $infoArr[0];
      $dbMod = $infoArr[1];
    }

    if($dbExists and $quick){
      $skippedCount++;
      next;
    }

    my $f = "$libpath/$songRelPath";
    if(not -f $f){
      print STDERR "file not found: $libpath/$songRelPath\n";
      next;
    }
    my $filesize = fsize $f;
    my $modified = mtime $f;

    if($dbExists and $dbSize == $filesize and $dbMod == $modified){
      $skippedCount++;
      next;
    }
    
    my $md5sum = '';

    my %tagInfo = Klomp::Tag::readTags "$libpath/$songRelPath";

    my %cols;
    for my $col(@tagCols){
      if(defined $tagInfo{$col}){
        $cols{$col} = $tagInfo{$col};
      }else{
        $cols{$col} = '';
      }
      $cols{$col . "_guess"} = Klomp::Tag::guess(
        $col, $songRelPath, $cols{$col});
    }
    
    $cols{library} = $lib;
    $cols{relpath} = $songRelPath;
    $cols{filesize} = $filesize;
    $cols{modified} = $modified;
    $cols{md5sum} = $md5sum;

    my @allVals;
    for my $col(@allCols){
      my $val = $cols{$col};
      chomp $val;
      $val =~ s/'/''/g;
      $val = "'$val'";
      push @allVals, $val;
    }

    print "$songRelPath\n";
    my $sqlPath = $songRelPath;
    $sqlPath =~ s/'/''/g;
    push @stmts, "delete from Songs where relpath='$sqlPath'";
    push @stmts, ''
      . " insert into Songs"
      . " (" . join(", ", @allCols) . ")"
      . " values"
      . " (" . join(", ", @allVals) . ")"
      ;

    if(++$count >= $limit){
      print "  adding $count  " .
        "{total: $songCount handled: $handledCount skipped: $skippedCount}\n";
      runSqlBatch $db, @stmts;
      $handledCount += $count;
      @stmts = ();
      $count = 0;
    }
  }
  if($count > 0){
    print "  adding $count  " .
      "{total: $songCount handled: $handledCount skipped: $skippedCount}\n";
    runSqlBatch $db, @stmts;
    $handledCount += $count;
    @stmts = ();
    $count = 0;
  }
  print "  handled $handledCount new or modified songs\n";
  print "  skipped $skippedCount unmodified songs {same size and mod date}\n";
}

sub wrapGuessCol($){
  my $col = shift;
  my $colGuess = $col . '_guess';
  return
    "IFNULL(".
      "NULLIF(".
        "$col,".
        "''".
      "),".
      "$colGuess)";
}

&main(@ARGV);
