#!/usr/bin/perl
use strict;
use warnings;

my $KLOMP_CLI_CMD = 'klomp';

my $PID_FILE = `klomp-files -n termpidfile`;
if(-e $PID_FILE){
  system "kill -0 `cat $PID_FILE` > /dev/null 2>/dev/null";
  die "Already running!\n" if $? == 0;
}
system "echo $$ > $PID_FILE";

system 'term', '-title', 'KLOMP', $KLOMP_CLI_CMD;
