#!/usr/bin/perl
use strict;
use warnings;
use lib "/opt/klomp/lib";
use Klomp::Files;
use Time::HiRes qw(sleep);

sub getPid();
sub setPid();

my $FIFO = Klomp::Files::klompFile("fifo");
my $PID_FILE = Klomp::Files::klompFile("fifopidfile");

sub main(@){
  die "Usage: $0\n" if @_ > 0;
  my $pid = getPid;
  system "kill", "-9", $pid if defined $pid;

  setPid;

  while(1){
    sleep 0.8;
    die "$FIFO is not a FIFO\n" if not -p $FIFO;
    die "New fifo writer is running\n" if $$ != getPid;
    open FIFO, "> $FIFO" or die "Couldn't open FIFO $FIFO for writing";
    print FIFO "pausing_keep_force get_time_length\n";
    print FIFO "pausing_keep_force get_time_pos\n";
    print FIFO "pausing_keep_force get_property pause\n";
    close FIFO;
  }
}

sub getPid(){
  if(-e $PID_FILE){
    my $pid = `cat $PID_FILE`;
    chomp $pid;
    if($pid =~ /^\d+$/){
      return $pid;
    }
  }
  return undef;
}

sub setPid(){
  open FH, "> $PID_FILE";
  print FH "$$\n";
  close FH;
}

&main(@ARGV);
