#!/usr/bin/perl
use strict;
use warnings;
use lib "/opt/klomp/lib";
use Klomp::Files;
use Klomp::Lib;

my $defaultKlomplib = Klomp::Files::klompFile("lib");

my $usage = "Usage:
  $0 [--file=libfile]
    print available libs
  $0 [--file=libfile] -p
    print library properties, one per line in the form \"<prop>=<val>\"
  $0 [--file=libfile] -d
    print default libs
  $0 [--file=libfile] -l LIB
    print library path for LIB
  $0 [--file=libfile] -f LIB
    print flacmirror path for LIB
  --file=libfile is optional, default is $defaultKlomplib\n";

sub main(@){
  my $klompLib = undef;
  if(@_ > 0 and $_[0] =~ /^--file=(.*)$/){
    $klompLib = $1;
    shift;
  }

  my $cmd = shift;
  my $arg = shift;
  die $usage if @_ > 0;

  if(not defined $cmd and not defined $arg){
    print map {"$_\n"} Klomp::Lib::getAllLibNames $klompLib;
  }elsif($cmd eq "-p" and not defined $arg){
    my $props = Klomp::Lib::getProperties $klompLib;
    print "$_ => $$props{$_}\n" foreach sort keys %$props;
  }elsif($cmd eq "-d" and not defined $arg){
    print map {"$_\n"} Klomp::Lib::getDefaultLibNames $klompLib;
  }elsif($cmd eq "-l" and defined $arg){
    print Klomp::Lib::getLibraryPath($arg, $klompLib) . "\n";
  }elsif($cmd eq "-f" and defined $arg){
    print Klomp::Lib::getFlacmirrorPath($arg, $klompLib) . "\n";
  }else{
    die $usage;
  }
}

&main(@ARGV);
