#!/usr/bin/python
#
#qtcmdplayer
#
#Copyright 2018 Elliot Wolk
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtMultimedia import *
from PyQt5.QtWidgets import *
import argparse
import bisect
import io
import os
import re
import sys
import signal
import time

BUFFER_LOG_FILE = "/tmp/qtcmdplayer-buffer.log"
CACHE_DIR = os.path.expanduser("~/.cache/qtcmdplayer")
BUFFER_CACHE_BYTES_FILE = CACHE_DIR + "/buffer-bytes.cache"
BUFFER_CACHE_INFO_FILE = CACHE_DIR + "/buffer-info.cache"
BUFFER_CACHE_AUDIOFORMAT_FILE = CACHE_DIR + "/buffer-audioformat.cache"
BUFFER_CACHE_LAST_SONG_INFO_FILE = CACHE_DIR + "/buffer-lastsonginfo.cache"

class PlayerType: QMEDIAPLAYER=1; QAUDIOOUTPUT=2

name = sys.argv[0]
parser = argparse.ArgumentParser(description=''
           + 'Play music/sound files from the command line using PyQt5 media tools.'
           )
parser.add_argument('FILE', type=str, help='sound file to play')
parser.add_argument('POSITION_MILLIS', type=int, nargs='?', default=0,
  help='optional starting position in millis')
parser.add_argument('COMMAND_FIFO', type=str, nargs='?',
  help='optional path to existing FIFO for listening to commands')

parser.add_argument('--daemon', '-daemon', required=False, default=False, action='store_const', const=True,  dest='DAEMON',
  help='disabled keyboard commands')

parser.add_argument('--loop', '-loop', required=False, default=False, action='store_const', const=True,  dest='LOOP',
  help='when playback is finished, play again immediately forever')

parser.add_argument('--volume', '-volume', type=int, default=100, required=False, dest='VOLUME',
  help='set volume 0 - 100'
       + '(values greater than 100 are allowed only for MP3s, or with --mp3)')

parser.add_argument('--mp3', required=False, dest='PLAYER_TYPE',
  action='store_const', const=PlayerType.QAUDIOOUTPUT,
  help='force MP3 mode regardless of file extension'
       + ' (use QAudioDecoder+QAudioOutput instead of QMediaPlayer)')
parser.add_argument('--nomp3', required=False, dest='PLAYER_TYPE',
  action='store_const', const=PlayerType.QMEDIAPLAYER,
  help='force non-MP3 mode regardless of file extension'
       + ' (use QMediaPlayer instead of QAudioDecoder+QAudioOutput)')

TERM = {"raw": False, "newline": "\n", "defaultTtyAttr": None}

def termSetRaw(isRaw):
  if isRaw != TERM["raw"]:
    import sys, tty, termios, os
    if TERM["defaultTtyAttr"] == None:
      TERM["defaultTtyAttr"] = termios.tcgetattr(sys.stdin.fileno())

    if isRaw:
      TERM["raw"] = True
      TERM["newline"] = "\r\n"
      tty.setraw(sys.stdin.fileno())
    else:
      TERM["raw"] = False
      TERM["newline"] = "\n"
      termios.tcsetattr(sys.stdin.fileno(), termios.TCSADRAIN, TERM["defaultTtyAttr"])

def printMsg(msg):
  sys.stdout.write(msg + TERM["newline"])
  sys.stdout.flush()

def printErr(msg):
  sys.stderr.write(msg + TERM["newline"])

def die(msg):
  termSetRaw(False)
  printErr(msg)
  sys.exit(1)

def quit():
  termSetRaw(False)
  sys.exit(0)

def printBufferLog(msg):
  with open(BUFFER_LOG_FILE, 'w') as log:
    log.write(msg)

def nowMillis():
  return int(time.time() * 1000 / 0.5)
def sleepUntil(intervalMillis, timeoutMillis, cond):
  startMillis = nowMillis()
  while not cond() and nowMillis() - startMillis < timeoutMillis:
    QThread.msleep(intervalMillis)

def rmFile(f):
  if os.path.isfile(f):
    os.remove(f)

def main():
  args = parser.parse_args()
  if args.POSITION_MILLIS < 0:
    die("ERROR: position must be non-negative")

  app = QApplication([])

  isExtMP3 = os.path.splitext(args.FILE)[1].lower() == ".mp3"

  playerType = args.PLAYER_TYPE
  if playerType == None:
    if not isExtMP3:
      playerType = PlayerType.QMEDIAPLAYER
    else:
      playerType = PlayerType.QAUDIOOUTPUT

  if playerType == PlayerType.QMEDIAPLAYER:
    player = QTCmdPlayer(args.FILE, args.POSITION_MILLIS, args.VOLUME, args.LOOP)
  elif playerType == PlayerType.QAUDIOOUTPUT:
    player = QTCmdPlayerMP3(args.FILE, args.POSITION_MILLIS, args.VOLUME, args.LOOP)
  else:
    die("unknown player type")

  if not args.DAEMON:
    termSetRaw(True)
    keyCmdReader = KeyCmdReader()
    keyCmdReader.keyCommandSignal.connect(player.onCommand)
    keyCmdReader.start()

  if args.COMMAND_FIFO != None:
    fifoReader = FIFOReader(args.COMMAND_FIFO)
    fifoReader.fifoCommandSignal.connect(player.onCommand)
    fifoReader.start()

  player.start()

  app.exec_()

class KeyCmdReader(QThread):
  keyCommandSignal = pyqtSignal(str)
  def __init__(self):
    QThread.__init__(self)
    self.readKey = ReadKey()
  def run(self):
    while True:
      for key in self.readKey.readKeys():
        if key == 'CTRL_C' or key == 'q' or key == 'Q':
          die("user quit\n")
        elif key == 'CTRL_Z':
          printMsg("user suspended")
          os.kill(os.getpid(), signal.SIGTSTP)
        elif key == 'Enter' or key == ' ':
          self.keyCommandSignal.emit('pause')
        elif key == 'Left':
          self.keyCommandSignal.emit('seek -10000')
        elif key == 'Right':
          self.keyCommandSignal.emit('seek +10000')
        elif key == 'Down':
          self.keyCommandSignal.emit('seek -60000')
        elif key == 'Up':
          self.keyCommandSignal.emit('seek +60000')

class FIFOReader(QThread):
  fifoCommandSignal = pyqtSignal(str)
  def __init__(self, fifoPath):
    QThread.__init__(self)
    self.fifoPath = fifoPath
  def run(self):
    while True:
      with open(self.fifoPath) as fifo:
        for cmd in fifo.read().splitlines():
          self.fifoCommandSignal.emit(cmd)

#doesnt allow seeking on MP3s
class QTCmdPlayer(QMediaPlayer):
  def __init__(self, songFile, initPos, volume, isLoop):
    QMediaPlayer.__init__(self)
    self.songFile = songFile
    self.initPos = initPos
    self.setVolume(volume)
    self.isLoop = isLoop

    self.started = False
    self.paused = False
    self.mediaStatusChanged.connect(self.onMediaStatusChanged)
    self.positionChanged.connect(self.onPositionChanged)
    self.error.connect(self.onError)
  def start(self):
    self.setMedia(QMediaContent(QUrl.fromLocalFile(self.songFile)))
  def onCommand(self, cmd):
    m = re.match('^\s*(play|pause)\s*$', cmd)
    if m:
      self.paused = not self.paused
      printMsg("paused=" + str(self.paused))
      if self.paused:
        self.pause()
      else:
        self.play()
      return

    m = re.match('^seek\s*(\+|-)?(\d+)$', cmd)
    if m:
      sign = m.group(1)
      seekPosMillis = int(m.group(2))
      if sign == None or sign == "":
        newPosMillis = seekPosMillis
      elif sign == "+":
        newPosMillis = self.position() + seekPosMillis
      elif sign == "-":
        newPosMillis = self.position() - seekPosMillis
      self.setPosition(newPosMillis)
  def onMediaStatusChanged(self, status):
    if(status == QMediaPlayer.LoadedMedia or status == QMediaPlayer.BufferedMedia):
      if not self.started:
        self.play()
        self.started = True
        self.setPosition(self.initPos)
    elif(status == QMediaPlayer.EndOfMedia):
      printMsg("END")
      if self.isLoop:
        self.play()
      else:
        quit()
  def onPositionChanged(self, pos):
    printMsg("pos: " + str(pos))
  def onError(self, msg):
    if self.errorString() != None:
      msg = self.errorString()
    else:
      msg = ""
    die("QMediaPlayer error: " + msg)

class PlayerThread(QThread):
  def __init__(self, player):
    QThread.__init__(self)
    self.player = player
  def run(self):
    self.player.playAvailableBuffers()

#doesnt work on flac at all
class QTCmdPlayerMP3(QObject):
  initAudioDeviceSignal = pyqtSignal()
  def __init__(self, songFile, initPos, volume, isLoop):
    QObject.__init__(self)
    self.songFile = songFile
    self.initSeekPos = initPos
    self.seekPosMicroSex = initPos * 1000
    self.volume = volume
    self.isLoop = isLoop

    self.position = 0
    self.bufferStartTimes = []
    self.bufferByteOffsets = []
    self.bufferByteSizes = []
    self.nextByteOffset = 0

    self.allBuffersLoaded = False
    self.paused = False

    self.waitingSeek = True
    self.curBufferIndex = None

    self.posIntervalMillis = 850
    self.lastPositionUpdateMillis = nowMillis()
    self.lastBufferPositionUpdateMillis = nowMillis()
    self.audioFormat = None
    self.lastBufferReadStartTime = None

    self.audioDecoder = QAudioDecoder()
    self.audioDecoder.bufferReady.connect(self.onBufferReady)
    self.audioDecoder.finished.connect(self.onFinished)
    self.audioDecoder.error.connect(self.onError)

    self.audioOutput = None
    self.audioDevice = None

    self.playerThread = PlayerThread(self)
    self.initAudioDeviceSignal.connect(self.initAudioDevice)

  def start(self):
    if FileCache(self.songFile, BUFFER_CACHE_LAST_SONG_INFO_FILE).compareCache():
      self.startFromCache()
    else:
      self.startFromDecoder()
  def startFromDecoder(self):
    if not os.path.isdir(CACHE_DIR):
      os.makedirs(CACHE_DIR)
    rmFile(BUFFER_CACHE_BYTES_FILE)
    rmFile(BUFFER_CACHE_INFO_FILE)
    rmFile(BUFFER_CACHE_AUDIOFORMAT_FILE)
    rmFile(BUFFER_CACHE_LAST_SONG_INFO_FILE)
    self.bufferCacheWriteFH = open(BUFFER_CACHE_BYTES_FILE, 'w')
    self.bufferCacheReadFH = open(BUFFER_CACHE_BYTES_FILE, 'r')

    self.audioDecoder.setSourceFilename(self.songFile)
    self.audioDecoder.start()
  def startFromCache(self):
    self.readBufferInfoCache()
    self.readAudioFormatCache()
    self.ensurePlaying()

    self.audioDecoder = None
    self.bufferCacheWriteFH = None
    self.bufferCacheReadFH = open(BUFFER_CACHE_BYTES_FILE, 'r')

    self.refreshAudioDevice()

    if self.waitingSeek:
      self.attemptSeek()
    else:
      self.ensurePlaying()
  def readBufferInfoCache(self):
    lines = None
    with open(BUFFER_CACHE_INFO_FILE, 'r') as f:
      lines = f.readlines()

    self.bufferStartTimes = []
    self.bufferByteOffsets = []
    self.bufferByteSizes = []
    self.nextByteOffset = 0
    for line in lines:
      m = re.match("^(\\d+) (\\d+)$", line)
      if m:
        startTime = int(m.group(1))
        byteSize = int(m.group(2))
        self.bufferStartTimes.append(startTime)
        self.bufferByteOffsets.append(self.nextByteOffset)
        self.bufferByteSizes.append(byteSize)
        self.nextByteOffset += byteSize
        self.lastBufferReadStartTime = startTime
      else:
        die("malformed buffer-info cache line: " + str(line))
    self.allBuffersLoaded = True
  def writeBufferInfoCache(self):
    with open(BUFFER_CACHE_INFO_FILE, 'w') as f:
      i = 0
      while i < len(self.bufferStartTimes):
        startTime = self.bufferStartTimes[i]
        byteSize = self.bufferByteSizes[i]
        f.write(str(startTime) + " " + str(byteSize) + "\n")
        i += 1
  def readAudioFormatCache(self):
    lines = None
    with open(BUFFER_CACHE_AUDIOFORMAT_FILE, 'r') as f:
      lines = f.readlines()

    self.audioFormat = QAudioFormat()
    for line in lines:
      intMatch = re.match("^(\\w+)\\s*=\\s*(\\d+)$", line)
      strMatch = re.match("^(\\w+)\\s*=\\s*(.+)$", line)
      if intMatch:
        key = intMatch.group(1)
        val = int(intMatch.group(2))
        if key == "sampleRate":
          self.audioFormat.setSampleRate(val)
        elif key == "sampleSize":
          self.audioFormat.setSampleSize(val)
        elif key == "sampleType":
          self.audioFormat.setSampleType(val)
        elif key == "channelCount":
          self.audioFormat.setChannelCount(val)
        elif key == "byteOrder":
          self.audioFormat.setByteOrder(val)
        else:
          die("unknown audio format key: " + str(key))
      elif strMatch:
        key = strMatch.group(1)
        val = strMatch.group(2)
        if key == "codec":
          self.audioFormat.setCodec(val)
        else:
          die("unknown audio format key: " + str(key))
      else:
        die("malformed audio format cache line: " + str(line))
  def writeAudioFormatCache(self):
    with open(BUFFER_CACHE_AUDIOFORMAT_FILE, 'w') as f:
      f.write("codec=" + str(self.audioFormat.codec()) + "\n")
      f.write("sampleRate=" + str(self.audioFormat.sampleRate()) + "\n")
      f.write("sampleSize=" + str(self.audioFormat.sampleSize()) + "\n")
      f.write("sampleType=" + str(self.audioFormat.sampleType()) + "\n")
      f.write("channelCount=" + str(self.audioFormat.channelCount()) + "\n")
      f.write("byteOrder=" + str(self.audioFormat.byteOrder()) + "\n")
  def bufferCount(self):
    return len(self.bufferStartTimes)
  def readBufferByteArr(self, index):
    byteSize = self.bufferByteSizes[index]
    byteOffset = self.bufferByteOffsets[index]
    self.bufferCacheReadFH.seek(byteOffset, io.SEEK_SET)
    return bytearray(self.bufferCacheReadFH.read(byteSize))
  def readBufferStartTime(self, index):
    return self.bufferStartTimes[index]
  def appendBuffer(self, byteArr, startTime):
    self.bufferCacheWriteFH.seek(0, io.SEEK_END)
    self.bufferCacheWriteFH.write(byteArr)

    byteSize = len(byteArr)
    byteOffset = self.nextByteOffset
    self.nextByteOffset += byteSize

    self.bufferStartTimes.append(startTime)
    self.bufferByteSizes.append(byteSize)
    self.bufferByteOffsets.append(byteOffset)

    self.onBufferPositionChanged(startTime)
  def onCommand(self, cmd):
    m = re.match('^\s*(play|pause)\s*$', cmd)
    if m:
      if self.paused:
        self.refreshAudioDevice()
      self.paused = not self.paused
      printMsg("paused=" + str(self.paused))
      return

    m = re.match('^seek\s*(\+|-)?(\d+)$', cmd)
    if m:
      sign = m.group(1)
      seekPosMillis = int(m.group(2))
      if sign == None or sign == "":
        newPosMillis = seekPosMillis
      elif sign == "+":
        newPosMillis = self.position + seekPosMillis
      elif sign == "-":
        newPosMillis = self.position - seekPosMillis
      self.waitingSeek = True
      self.seekPosMicroSex = newPosMillis * 1000
      self.stopPlaying()
      self.attemptSeek()
  def refreshAudioDevice(self):
    if self.audioFormat != None:
      self.audioOutput = None
      self.audioDevice = None
      self.initAudioDeviceSignal.emit()
      sleepUntil(1, 1000, lambda: self.audioDevice != None)
  def initAudioDevice(self):
    if self.audioFormat != None:
      self.audioOutput = QAudioOutput(self.audioFormat, self)
      self.audioDevice = self.audioOutput.start()
      self.audioOutput.setVolume(self.volume / 100.0)
  def onBufferReady(self):
    buf = self.audioDecoder.read()
    startTime = buf.startTime()
    byteArr = self.bufferToByteArray(buf)

    if self.audioFormat == None:
      self.audioFormat = buf.format()

    self.lastBufferReadStartTime = startTime

    self.appendBuffer(byteArr, startTime)

    if self.audioOutput == None or self.audioDevice == None:
      self.refreshAudioDevice()

    if self.waitingSeek:
      self.attemptSeek()
    else:
      self.ensurePlaying()
  def attemptSeek(self):
    index = bisect.bisect_left(self.bufferStartTimes, self.seekPosMicroSex)
    if index >= 0 and index < self.bufferCount():
      self.curBufferIndex = index
      self.waitingSeek = False
      bufferPos = self.readBufferStartTime(index)
      self.position = int(bufferPos / 1000.0 + 0.5)
      self.onPositionChanged(self.position)

    self.maybeQuit()
  def maybeQuit(self):
    if self.isSongOver():
      printMsg("END")
      if self.isLoop:
        self.seekPosMicroSex = self.initSeekPos * 1000
        self.attemptSeek()
        self.start()
      else:
        quit()
  def isSongOver(self):
    if not self.allBuffersLoaded:
      return False
    elif self.curBufferIndex >= self.bufferCount():
      return True
    elif self.bufferCount() == 0:
      return True
    elif self.seekPosMicroSex > self.lastBufferReadStartTime:
      return True
    else:
      return False
  def ensurePlaying(self):
    if not self.isPlaying():
      self.playerThread.start()
  def stopPlaying(self):
    self.playerThread.quit()
  def isPlaying(self):
    return self.playerThread.isRunning()
  def isReadyToPlay(self):
    return not self.paused and not self.waitingSeek and self.isBufferAvailable()
  def isBufferAvailable(self):
    return self.curBufferIndex >= 0 and self.curBufferIndex < self.bufferCount()
  def playAvailableBuffers(self):
    while True:
      sleepUntil(100, 1000, self.isReadyToPlay)

      while self.isReadyToPlay():
        bufferPos = self.readBufferStartTime(self.curBufferIndex)
        byteArray = self.readBufferByteArr(self.curBufferIndex)
        self.playBuffer(byteArray, bufferPos)
        self.curBufferIndex += 1

      self.maybeQuit()
  def bufferToByteArray(self, audioBuffer):
    byteStr = audioBuffer.data().asstring(audioBuffer.byteCount())
    return bytearray(byteStr)
  def playBuffer(self, audioBufferByteArr, bufferPos):
    bufferSize = len(audioBufferByteArr)

    sleepUntil(1, 1000, lambda: self.audioOutput.bytesFree() >= bufferSize)

    if self.audioOutput.bytesFree() < bufferSize:
      printErr("WAITING OVER A SECOND FOR AUDIO DEVICE, RE-INTIIALIZING")
      self.refreshAudioDevice()
      sleepUntil(1, 1000, lambda: self.audioOutput.bytesFree() >= bufferSize)

    if self.volume > 100:
      audioBufferByteArr = self.scaleVolumeByteArr(audioBufferByteArr, self.volume)

    self.audioDevice.write(audioBufferByteArr)
    self.position = int(bufferPos / 1000.0 + 0.5)
    self.onPositionChanged(self.position)
  def scaleVolumeByteArr(self, byteArr, volume):
    samples = self.getSamplesFromByteArr(byteArr)

    if volume < 100:
      die("can only scale volume upwards for some reason")

    volScale = 1 + (volume - 100)/100.0 * 3 #100%-200% => 1-4

    newByteArr = bytearray()
    for sample in samples:
      sample = self.multiplyByteArr(sample, volScale)
      for byte in sample:
        newByteArr.append(byte)

    return newByteArr
  def getSamplesFromByteArr(self, byteArr):
    samples = []
    curSample = bytearray()
    for byte in byteArr:
      if len(curSample) >= int(self.audioFormat.sampleSize()/8):
        samples.append(curSample)
        curSample = bytearray()
      curSample.append(byte)
    if len(curSample) > 0:
      samples.append(curSample)
    return samples
  def multiplyByteArr(self, byteArr, scale):
    val = 0
    place = 0
    for byte in byteArr:
      val += byte * (256**place)
      place += 1
    oldVal = val
    val = val * scale
    if val >= 256**place:
      val = 256**place - 1
    newByteArr = bytearray()
    for i in range(0, place):
      byte = int(val) % 256
      val = val / 256
      newByteArr.append(byte)
    return newByteArr
  def formatLastBufferPos(self):
    if self.lastBufferReadStartTime == None:
      return ""
    else:
      return '%.2fs' % (self.lastBufferReadStartTime / 1000000.0)
  def onPositionChanged(self, position):
    if nowMillis() - self.lastPositionUpdateMillis >= self.posIntervalMillis:
      self.lastPositionUpdateMillis = nowMillis()
      printMsg("pos: " + str(position))
  def onBufferPositionChanged(self, bufferPosition):
    if nowMillis() - self.lastBufferPositionUpdateMillis >= self.posIntervalMillis:
      self.lastBufferPositionUpdateMillis = nowMillis()
      printBufferLog(self.formatLastBufferPos())
  def onFinished(self):
    self.allBuffersLoaded = True
    printBufferLog("finished: " + self.formatLastBufferPos())

    self.writeBufferInfoCache()
    self.writeAudioFormatCache()

    FileCache(self.songFile, BUFFER_CACHE_LAST_SONG_INFO_FILE).writeInfoCache()
  def onError(self):
    if self.audioDecoder != None and self.audioDecoder.errorString() != None:
      msg = self.audioDecoder.errorString()
    else:
      msg = ""
    die("QAudioDecoder error: " + msg)

class FileCache:
  def __init__(self, srcFile, infoCacheFile):
    self.srcFile = srcFile
    self.infoCacheFile = infoCacheFile
  def getSrcFileMtime(self):
    return int(os.path.getmtime(self.srcFile))
  def getSrcFileSize(self):
    return int(os.path.getsize(self.srcFile))
  def readInfoCache(self):
    try:
      with open(self.infoCacheFile, 'r') as f:
        s = f.read()
        m = re.match("^(\\d+) (\\d+) (.+)$", s)
        if m:
          return { "mtime": int(m.group(1))
                 , "size": int(m.group(2))
                 , "path": m.group(3)
                 }
        else:
          return None
    except:
      return None
  def writeInfoCache(self):
    with open(self.infoCacheFile, 'w') as f:
      f.write("%d %d %s" % (self.getSrcFileMtime(), self.getSrcFileSize(), self.srcFile))
  def compareCache(self):
    info = self.readInfoCache()
    return (
      info != None
      and info["path"] == self.srcFile
      and info["mtime"] == self.getSrcFileMtime()
      and info["size"] == self.getSrcFileSize()
    )

class ReadKey:
  def __init__(self):
    self.fileno = sys.stdin.fileno()
    self.ttyAttr = None
    self.keyBytes = { 0x03: "CTRL_C"
                    , 0x1a: "CTRL_Z"
                    , 0x09: "Tab"
                    , 0x0A: "Enter"
                    , 0x0D: "Enter"
                    , 0x7F: "BackSpace"
                    }
    self.seqByte = 0x1b
    self.seqs = { "Up":        ['[', 'A']
                , "Down":      ['[', 'B']
                , "Right":     ['[', 'C']
                , "Left":      ['[', 'D']
                , "Home":      ['[', '7', '~']
                , "End":       ['[', '8', '~']
                , "Insert":    ['[', '2', '~']
                , "Delete":    ['[', '3', '~']
                , "Page_Up":   ['[', '5', '~']
                , "Page_Down": ['[', '6', '~']
                , "F1":        ['[', '1', '1', '~']
                , "F2":        ['[', '1', '2', '~']
                , "F3":        ['[', '1', '3', '~']
                , "F4":        ['[', '1', '4', '~']
                , "F5":        ['[', '1', '5', '~']
                , "F6":        ['[', '1', '7', '~']
                , "F7":        ['[', '1', '8', '~']
                , "F8":        ['[', '1', '9', '~']
                , "F9":        ['[', '2', '0', '~']
                , "F10":       ['[', '2', '1', '~']
                , "F11":       ['[', '2', '3', '~']
                , "F12":       ['[', '2', '4', '~']
                , "Escape":    []
                }
    self.seqsLongestFirst = sorted(
      self.seqs.keys(),
      key=lambda keyName: len(self.seqs[keyName]),
      reverse=True)
  def readKeys(self):
    keyBytes = self.readBytes()
    keys = []
    while len(keyBytes) > 0:
      firstByte = keyBytes.pop(0)
      if firstByte in self.keyBytes:
        keys.append(self.keyBytes[firstByte])
      elif firstByte == self.seqByte:
        for keyName in self.seqsLongestFirst:
          byteSeq = bytearray(self.seqs[keyName])
          if self.isArrPrefix(keyBytes, byteSeq):
            keys.append(keyName)
            for byte in byteSeq:
              keyBytes.pop(0)
            break
      elif firstByte >= 0xc2 and firstByte <= 0xdf:
        byteArr = [firstByte]
        if len(keyBytes) > 0:
          byteArr.append(keyBytes.pop(0))
        keys.append(bytearray(byteArr).decode('utf-8'))
      elif firstByte >= 0xe0 and firstByte <= 0xef and len(keyBytes) >= 2:
        byteArr = [firstByte]
        if len(keyBytes) > 0:
          byteArr.append(keyBytes.pop(0))
        if len(keyBytes) > 0:
          byteArr.append(keyBytes.pop(0))
        keys.append(bytearray(byteArr).decode('utf-8'))
      else:
        keys.append(chr(firstByte))
    return keys
  def isArrPrefix(self, arr, prefixArr):
    for i in range(0, len(prefixArr)):
      if i >= len(arr) or arr[i] != prefixArr[i]:
        return False
    return True
  def readBytes(self):
    return bytearray(os.read(self.fileno, 64))

if __name__ == "__main__":
  sys.exit(main())
