#!/usr/bin/python
#
#qtcmdplayer
#
#Copyright 2018 Elliot Wolk
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtMultimedia import *
from PyQt5.QtWidgets import *
import bisect
import os
import re
import sys
import signal
import time

name = sys.argv[0]
usage = ("Usage:\n"
  + "  " + name + " FILE [POSITION_MILLIS] [COMMAND_FIFO]\n"
)

def printErr(msg):
  sys.stderr.write(msg + "\n")

def nowMillis():
  return int(time.time() * 1000 / 0.5)

def main():
  if len(sys.argv) == 2 and sys.argv[1] == '-h':
    print(usage)
    return 0
  elif len(sys.argv) == 2:
    fileName = sys.argv[1]
    pos = 0
    fifoPath = None
  elif len(sys.argv) == 3 and re.match('^\d+$', sys.argv[2]):
    fileName = sys.argv[1]
    pos = int(sys.argv[2])
    fifoPath = None
  elif len(sys.argv) == 4 and re.match('^\d+$', sys.argv[2]):
    fileName = sys.argv[1]
    pos = int(sys.argv[2])
    fifoPath = sys.argv[3]
  else:
    printErr(usage)
    return 1

  app = QApplication([])

  if os.path.splitext(fileName)[1].lower() == ".mp3":
    player = QTCmdPlayerMP3(fileName, pos)
  else:
    player = QTCmdPlayer(fileName, pos)

  if fifoPath != None:
    fifoReader = FIFOReader(fifoPath)
    fifoReader.fifoCommandSignal.connect(player.onCommand)
    fifoReader.start()

  player.start()

  app.exec_()

class FIFOReader(QThread):
  fifoCommandSignal = pyqtSignal(str)
  def __init__(self, fifoPath):
    QThread.__init__(self)
    self.fifoPath = fifoPath
  def run(self):
    while True:
      with open(self.fifoPath) as fifo:
        for cmd in fifo.read().splitlines():
          self.fifoCommandSignal.emit(cmd)

#doesnt allow seeking on MP3s
class QTCmdPlayer(QMediaPlayer):
  def __init__(self, songFile, initPos):
    QMediaPlayer.__init__(self)
    self.songFile = songFile
    self.initPos = initPos

    self.started = False
    self.paused = False
    self.mediaStatusChanged.connect(self.onMediaStatusChanged)
    self.positionChanged.connect(self.onPositionChanged)
  def start(self):
    self.setMedia(QMediaContent(QUrl.fromLocalFile(self.songFile)))
  def onCommand(self, cmd):
    m = re.match('^\s*(play|pause)\s*$', cmd)
    if m:
      self.paused = not self.paused
      print "paused=" + str(self.paused)
      if self.paused:
        self.pause()
      else:
        self.play()
      return
    m = re.match('^seek\s*(\d+)$', cmd)
    if m:
      self.setPosition(int(m.group(1)))
  def onMediaStatusChanged(self, status):
    if(status == QMediaPlayer.LoadedMedia or status == QMediaPlayer.BufferedMedia):
      if not self.started:
        self.play()
        self.started = True
        self.setPosition(self.initPos)
    elif(status == QMediaPlayer.EndOfMedia):
      print("END")
      sys.exit(0)
  def onPositionChanged(self, pos):
    print("pos: " + str(pos))
    sys.stdout.flush()

class PlayerThread(QThread):
  def __init__(self, player):
    QThread.__init__(self)
    self.player = player
  def run(self):
    self.player.playAvailableBuffers()

#doesnt work on flac at all
class QTCmdPlayerMP3:
  def __init__(self, songFile, seekPos):
    self.songFile = songFile
    self.seekPosMicroSex = seekPos * 1000
    self.buffers = []
    self.bufferStartTimesMicroSex = []

    self.allBuffersLoaded = False

    self.waitingSeek = True
    self.curBufferIndex = None

    self.posIntervalMillis = 850
    self.lastPositionUpdateMillis = nowMillis()

    self.audioDecoder = QAudioDecoder()
    self.audioDecoder.bufferReady.connect(self.onBufferReady)
    self.audioDecoder.finished.connect(self.onFinished)

    self.audioOutput = None
    self.audioDevice = None

    self.playerThread = PlayerThread(self)
  def start(self):
    self.audioDecoder.setSourceFilename(self.songFile)
    self.audioDecoder.start()
  def onCommand(self, cmd):
    pass
  def onBufferReady(self):
    b = self.audioDecoder.read()
    if self.audioOutput == None or self.audioDevice == None:
      self.audioOutput = QAudioOutput(b.format(), self.audioDecoder)
      self.audioDevice = self.audioOutput.start()

    self.buffers.append(b)
    self.bufferStartTimesMicroSex.append(b.startTime())

    if self.waitingSeek:
      self.attemptSeek()
    else:
      self.ensurePlaying()
  def attemptSeek(self):
    index = bisect.bisect_left(self.bufferStartTimesMicroSex, self.seekPosMicroSex)
    if index >= 0 and index < len(self.buffers):
      self.curBufferIndex = index
      self.waitingSeek = False
      self.onPositionChanged(int(self.buffers[index].startTime() / 1000.0 + 0.5))

    self.maybeQuit()
  def maybeQuit(self):
    if self.isSongOver():
      print("END")
      sys.exit(0)
  def isSongOver(self):
    if not self.allBuffersLoaded:
      return False
    elif self.curBufferIndex >= len(self.buffers):
      return True
    elif len(self.bufferStartTimesMicroSex) == 0:
      return True
    elif self.seekPosMicroSex > self.bufferStartTimesMicroSex[-1]:
      return True
    else:
      return False
  def ensurePlaying(self):
    if not self.isPlaying():
      self.playerThread.start()
  def stopPlaying(self):
    self.playerThread.quit()
  def isPlaying(self):
    return self.playerThread.isRunning()
  def playAvailableBuffers(self):
    while True:
      if self.waitingSeek:
        QThread.msleep(100)

      while self.curBufferIndex >= 0 and self.curBufferIndex < len(self.buffers):
        if self.waitingSeek:
          break
        self.playBuffer(self.buffers[self.curBufferIndex])
        self.curBufferIndex += 1

      self.maybeQuit()
  def playBuffer(self, audioBuffer):
    byteStr = audioBuffer.data().asstring(audioBuffer.byteCount())
    byteArr = QByteArray.fromRawData(byteStr)
    while(self.audioOutput.bytesFree() < audioBuffer.byteCount()):
      QThread.msleep(1)
    self.audioDevice.write(byteArr)
    self.onPositionChanged(int(audioBuffer.startTime() / 1000.0 + 0.5))
  def onPositionChanged(self, position):
    if nowMillis() - self.lastPositionUpdateMillis >= self.posIntervalMillis:
      self.lastPositionUpdateMillis = nowMillis()
      print "pos: " + str(position)
      sys.stdout.flush()
  def onFinished(self):
    self.allBuffersLoaded = True

if __name__ == "__main__":
  sys.exit(main())
